version: '3.9'

services:
  database:
    image: postgres:17.2
    container_name: rba_database
    environment:
      POSTGRES_DB: rba
      POSTGRES_USER: rba_user
      POSTGRES_PASSWORD: rba_pass
    ports:
      - "5432:5432"
